FROM runningman84/rainloop:latest
MAINTAINER Ibrahim Folarin <ifolarin@webbasedsol.com>

COPY bootstrap/application.ini /var/www/html/data/_data_/_default_/configs/
COPY bootstrap/default.ini /var/www/html/rainloop/v/1.11.3/app/domains/
